# Generated by Django 2.0.2 on 2018-03-03 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alpha',
            name='new_field',
            field=models.CharField(default='', max_length=10),
        ),
    ]
